// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGax_gmpBGRGkvAqc3Cc4IX_0IWLbVQRQ',
    appId: '1:1057884756342:web:7ae90addb20b431db8c257',
    messagingSenderId: '1057884756342',
    projectId: 'healthmate-81e13',
    authDomain: 'healthmate-81e13.firebaseapp.com',
    storageBucket: 'healthmate-81e13.appspot.com',
    measurementId: 'G-2N99Y7HF24',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCifH1Lancozf8HO0oaRmQs8fPeLc7T3C4',
    appId: '1:1057884756342:android:1612a10f7e5b176bb8c257',
    messagingSenderId: '1057884756342',
    projectId: 'healthmate-81e13',
    storageBucket: 'healthmate-81e13.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXUGIvRNfWOjxlRNufT1KJ-g10-zznwuE',
    appId: '1:1057884756342:ios:e00fbbf9a14975b7b8c257',
    messagingSenderId: '1057884756342',
    projectId: 'healthmate-81e13',
    storageBucket: 'healthmate-81e13.appspot.com',
    iosBundleId: 'com.example.healthMate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXUGIvRNfWOjxlRNufT1KJ-g10-zznwuE',
    appId: '1:1057884756342:ios:c764a35ceff06471b8c257',
    messagingSenderId: '1057884756342',
    projectId: 'healthmate-81e13',
    storageBucket: 'healthmate-81e13.appspot.com',
    iosBundleId: 'com.example.healthMate.RunnerTests',
  );
}
